### ISSUE TITLE
ImportError: cannot import name constants when upgrading from 2.4.1 to 2.5.2

### ISSUE THREAD

**Issue by dwsc** [GoogleCloudPlatform/compute-image-packages#462]
My instances upgraded from 2.4.1 to 2.5.2 and importing boto fails as follows.  Rolling back to 2.4.1 fixes the issue.

```
from boto import connect_s3, connect_gs
  File "/home/something/.virtualenvs/something/lib/python2.7/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/home/something/.virtualenvs/something/lib/python2.7/site-packages/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/home/something/.virtualenvs/something/lib/python2.7/site-packages/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/usr/lib/python2.7/site-packages/google_compute_engine/boto/boto_config.py", line 30, in <module>
    from google_compute_engine import constants
ImportError: cannot import name constants
```

**Comment by zmarano** [comment]
Are you installing the pypi package for google-compute-engine in the virtualenv? If so, you probably need to update it to that it includes the new constants file.

**Comment by zmarano** [comment]
Please let us know if upgrading your virtual env package works. Re-open this issue if you run into problems.

**Comment by dwsc** [comment]
Yes, updating the google-compute-engine and boto packages corrected the issue.  Thanks.
